acl atk0net { 172.20.44.0/24; 172.25.44.0/28; 172.30.44.0/24;  fd20:aa44:babe:20::/64; fd25:aa44:cafe:25::/64; fd30:aa44:babe:30::/64; };
key "ddns." { algorithm hmac-sha256; secret "Dz2tZEYuFY41o1SvTWrMbCuJXfJOvJmmsBv+LC/wZcA="; };

options {
    directory "/var/named/";
    listen-on-v6 { atk0net;localhost; };
    listen-on { atk0net;localhost; };
    version "why";
    
    recursion yes;
    qname-minimization strict;
    allow-query { atk0net; };
    empty-zones-enable yes;
    allow-recursion { atk0net; };
    allow-query-cache { atk0net; };
    dnssec-validation auto;
    dnssec-policy default;
    prefetch 5;
    min-cache-ttl 90;
    max-cache-ttl 604800;
};
// Zonefiles
zone "." {
    type hint;
    file "named.root"; };

zone "lamb" {
    type master;
    file "zonefiles.lamb.d/zf.lamb4";
    update-policy { grant ddns. zonesub any; };
    inline-signing yes;
    checkds no;
    allow-query { atk0net; };
};

zone "cntrl" {
    type master;
    file "zonefiles.lamb.d/zf.cntrl4";
    update-policy { grant ddns. zonesub any; };
    inline-signing yes;
    checkds no;
    allow-query { atk0net; };
};


zone "accp" {
    type master;
    file "zonefiles.lamb.d/zf.accp4";
    update-policy { grant ddns. zonesub any; };
    inline-signing yes;
    checkds no;
    allow-query { atk0net; };
};

zone "44.20.172.in-addr.arpa" {
    type master;
    file "zonefiles.lamb.d/zf.ptr.lamb4";
    update-policy { grant ddns. zonesub any; };
    inline-signing yes;
    checkds no;
    allow-query { atk0net; };
};

zone "44.25.172.in-addr.arpa" {
    type master;
    file "zonefiles.lamb.d/zf.ptr.cntrl4";
    update-policy { grant ddns. zonesub any; };
    inline-signing yes;
    checkds no;
    allow-query { atk0net; };
};

zone "44.30.172.in-addr.arpa" {
    type master;
    file "zonefiles.lamb.d/zf.ptr.accp4";
    update-policy { grant ddns. zonesub any; };
    inline-signing yes;
    checkds no;
    allow-query { atk0net; };
};

zone "0.2.0.0.e.b.a.b.4.4.a.a.0.2.d.f.ip6.arpa" {
    type master;
    file "zonefiles.lamb.d/zf.ptr.lamb6";
    update-policy { grant ddns. zonesub any; };
    inline-signing yes;
    checkds no;
    allow-query { atk0net; };
};

zone "5.2.0.0.e.f.a.c.4.4.a.a.5.2.d.f.ip6.arpa" {
    type master;
    file "zonefiles.lamb.d/zf.ptr.cntrl6";
    update-policy { grant ddns. zonesub any; };
    inline-signing yes;
    checkds no;
    allow-query { atk0net; };
};

zone "0.3.0.0.e.b.a.b.4.4.a.a.0.3.d.f.ip6.arpa" {
    type master;
    file "zonefiles.lamb.d/zf.ptr.accp6";
    update-policy { grant ddns. zonesub any; };
    inline-signing yes;
    checkds no;
    allow-query { atk0net; };
};
