# Configuration file for dnsmasq.
#
no-resolv
server=127.0.0.1#5353
server=::1#5353
dhcp-authoritative
domain-needed
bogus-priv
clear-on-reload
max-cache-ttl=3600
dnssec
keep-in-foreground
port-limit=3
dhcp-fqdn
all-servers

# vlan interface
except-interface=enp0s21f0u2u4
except-interface=wlp2s0
interface=eno1

# Authoritative settings
dhcp-authoritative
auth-ttl=3600
local-ttl=300

# vlan 20 /lamb/ dhcp and dns settings
interface=lamb
interface-name=salr.lamb,lamb
auth-server=slar.lamb,lamb
#==========DHCP===========#
tag-if=set:lamb,tag:lamb
dhcp-range=set:lamb,172.20.44.100,172.20.44.250,255.255.255.0,12h
dhcp-range=set:lamb,::,constructor:lamb,ra-names,ra-stateless,slaac
dhcp-option=tag:lamb,3,172.20.44.254
dhcp-option=tag:lamb,6,172.20.44.254
dhcp-option=tag:lamb,option6:dns-server,[fd20:aa44:babe:20:254]
#======Local-Domain=======#
auth-zone=lamb,172.20.44.0/24,fd20:aa44:babe:20::0/64
domain=lamb,172.20.44.0/24
local=/lamb/
server=/lamb/172.20.44.254

# vlan 25 /cntrl/ dhcp and dns settings
interface=cntrl
interface-name=salr.cntrl,cntrl
auth-server=salr.cntrl,cntrl
#==========DHCP===========#
tag-if=set:cntrl,tag:cntrl
dhcp-range=set:cntrl,172.25.44.0,255.255.255.240
dhcp-range=set:cntrl,::,static
dhcp-option=tag:cntrl,3,172.25.44.14
dhcp-option=tag:cntrl,6,172.25.44.14
dhcp-option=tag:cntrl,option6:dns-server,[fd25:aa44:cafe:25:14]
#======Local-Domain=======#
auth-zone=cntrl,172.25.44.0/28,fd25:aa44:cafe:25::0/64
domain=cntrl,172.25.44.0/28
local=/cntrl/
server=/cntrl/172.25.44.14


# vlan 30 /accp/ dhcp and dns settings
interface=accp
interface-name=salr.accp,accp
auth-server=salr.accp,accp
#==========DHCP===========#
tag-if=set:accp,tag:accp
dhcp-range=set:accp,172.30.44.50,172.30.44.250,255.255.255.0,12h
dhcp-range=set:accp,::,constructor:accp,ra-names,ra-stateless,slaac
dhcp-option=tag:accp,3,172.30.44.1
dhcp-option=tag:accp,6,172.30.44.1
dhcp-option=tag:accp,option6:dns-server,[fd30:aa44:babe:30:1]
#======Local-Domain=======#
auth-zone=accp,172.30.44.0/24,fd30:aa44:babe:30::0/64
domain=accp,172.30.44.0/24
local=/accp/
server=/accp/172.30.44.1

# DHCP Hosts
addn-hosts=/etc/dnsmasq.hosts
dhcp-host=4a:4b:45:2d:98:f8,ao,172.20.44.4,infinite
dhcp-host=c8:1f:66:ec:d1:5d,proxmox,172.20.44.5,infinite
dhcp-host=c8:1f:66:ec:d1:5f,proxmox,172.20.44.3,infinite
expand-hosts

log-dhcp
log-queries
cache-size=10000
dhcp-rapid-commit
dhcp-option=option:ntp-server,192.168.0.4,10.10.0.5

