# Configuration file for dnsmasq.
#
no-resolv
server=9.9.9.9
server=1.1.1.1
dhcp-authoritative
domain-needed
bogus-priv
clear-on-reload
# vlan interface
except-interface=enp0s21f0u2u4
except-interface=wlp2s0
interface=eno1

# vlan 1 /cntrl.lamb/ dhcp and dns settings
interface=vlan.1
#==========DHCP===========#
dhcp-range=set:vlan1,10.0.1.0,static,255.255.255.248
dhcp-option=tag:vlan1,3,10.0.1.1
dhcp-option=tag:vlan1,6,10.0.1.1
#======Local-Domain=======#
domain=cntrl.lamb,10.0.1.0/29
local=/cntrl.lamb/
server=/cntrl.lamb/10.0.1.1

# vlan 10 /wrk.lamb/ dhcp and dns settings
interface=vlan.10
#==========DHCP===========#
dhcp-range=set:vlan10,10.0.10.4,10.0.10.14,255.255.255.240,12h
dhcp-option=tag:vlan10,3,10.0.10.1
dhcp-option=tag:vlan10,6,10.0.10.1
#======Local-Domain=======#
domain=wrk.lamb,10.0.10.0/28
local=/wrk.lamb/
server=/wrk.lamb/10.0.10.1


# vlan 20 /server.lamb/ dhcp and dns settings
interface=vlan.20
#==========DHCP===========#
dhcp-range=set:vlan20,10.0.20.31,10.0.20.62,255.255.255.192,12h
dhcp-option=tag:vlan20,3,10.0.20.1
dhcp-option=tag:vlan20,6,10.0.20.1
#======Local-Domain=======#
domain=server.lamb,10.0.20.0/26
local=/server.lamb/
server=/server.lamb/10.0.20.1

# vlan 30 /lab-env.lamb/ dhcp and dns settings
interface=vlan.30
#===========DCHP==========#
dhcp-range=set:vlan30,10.0.30.10,10.0.30.254,255.255.255.0,12h
dhcp-option=tag:vlan30,3,10.0.30.1
dhcp-option=tag:vlan30,6,10.0.30.1
#======Local-Domain=======#
domain=lab-env.lamb,10.0.30.0/24
local=/lab-env.lamb/
server=/lab-env.lamb/10.0.30.1


# vlan 40 /dmz.lamb/ dhcp and dns settings
interface=vlan.40
#==========DHCP===========#
dhcp-range=set:vlan40,10.0.40.10,10.0.40.14,255.255.255.240,12h
dhcp-option=tag:vlan40,3,10.0.40.1
dhcp-option=tag:vlan30,6,10.0.40.1
#======Local-Domain======#
domain=dmz.lamb,10.0.40.0/28
local=/dmz.lamb/
server=/dmz.lamb/10.0.40.1


# vlan 50 /wifi.lamb/
interface=vlan.50
#==========DHCP==========#
dhcp-range=set:vlan50,10.0.50.3,10.0.50.254,255.255.255.0,12h
dhcp-option=tag:vlan50,3,10.0.50.1
dhcp-option=tag:vlan50,6,10.0.50.1
#======Local-Domain======#
domain=wifi.lamb,10.0.50.0/24
local=/wifi.lamb/
server=/wifi.lamb/8.8.8.8

# DHCP Hosts
addn-hosts=/etc/dnsmasq.hosts
dhcp-host=02:0c:6b:9a:5a:a0,apNG,10.0.50.2
dhcp-host=4a:4b:45:2d:98:f8,archomen,10.0.10.2,infinite
dhcp-host=c8:1f:66:ec:d1:5d,proxmox,10.0.20.3,infinite
dhcp-host=c8:1f:66:ec:d1:5f,proxmox,10.0.30.3,infinite
expand-hosts

log-dhcp
log-queries
cache-size=10000
dhcp-rapid-commit
dhcp-option=option:ntp-server,192.168.0.4,10.10.0.5

